In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
loans_df = pd.read_csv('loan_status.csv')
loans_df

,Loan_Status,Current_Loan_Amount,Term,Credit_Score,Annual_Income,Years_in_current_job,Home_Ownership,Purpose,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,Bankruptcies,Tax_Liens
0,Fully_Paid,99999999,Short_Term,741.0,2231892.0,8_years,Own_Home,Debt_Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
1,Fully_Paid,217646,Short_Term,730.0,1184194.0,<_1_year,Home_Mortgage,Debt_Consolidation,10855.08,19.6,10.0,13,1,122170,272052.0,1.0,0.0
2,Fully_Paid,548746,Short_Term,678.0,2559110.0,2_years,Rent,Debt_Consolidation,18660.28,22.6,33.0,4,0,437171,555038.0,0.0,0.0
3,Fully_Paid,99999999,Short_Term,728.0,714628.0,3_years,Rent,Debt_Consolidation,11851.06,16.0,76.0,16,0,203965,289784.0,0.0,0.0
4,Fully_Paid,99999999,Short_Term,740.0,776188.0,<_1_year,Own_Home,Debt_Consolidation,11578.22,8.5,25.0,6,0,134083,220220.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36418,Fully_Paid,99999999,Short_Term,742.0,1190046.0,<_1_year,Rent,Other,11969.81,20.1,16.0,9,0,37392,134442.0,0.0,0.0
36419,Fully_Paid,44484,Short_Term,717.0,1152426.0,10+_years,Home_Mortgage,Other,6280.64,21.0,12.0,6,0,961932,0.0,0.0,0.0
36420,Fully_Paid,210584,Short_Term,719.0,783389.0,1_year,Home_Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
36421,Fully_Paid,99999999,Short_Term,732.0,1289416.0,1_year,Rent,Debt_Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
36422,Fully_Paid,103136,Short_Term,742.0,1150545.0,6_years,Rent,Debt_Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0

In [3]:
# Generate our categorical variable list
loans_cat = loans_df.dtypes[loans_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
loans_df[loans_cat].nunique()

Loan_Status              2
Term                     2
Years_in_current_job    11
Home_Ownership           4
Purpose                  7
dtype: int64

In [4]:
# Check the unique value counts to see if binning is required
loans_df.Years_in_current_job.value_counts()
#there is substantial data in each so we don't need to bucket

10+_years    13149
2_years       3225
3_years       2997
<_1_year      2699
5_years       2487
4_years       2286
1_year        2247
6_years       2109
7_years       2082
8_years       1675
9_years       1467
Name: Years_in_current_job, dtype: int64

In [5]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(loans_df[loans_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(loans_cat)
encode_df

,Loan_Status_Fully_Paid,Loan_Status_Not_Paid,Term_Long_Term,Term_Short_Term,Years_in_current_job_10+_years,Years_in_current_job_1_year,Years_in_current_job_2_years,Years_in_current_job_3_years,Years_in_current_job_4_years,Years_in_current_job_5_years,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36418,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36419,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36420,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36421,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
36422,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [6]:
# Merge one-hot encoded features and drop the originals
loans_df = loans_df.merge(encode_df,left_index=True, right_index=True)
loans_df = loans_df.drop(loans_cat,1)
loans_df

/Users/emilymaynard/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Current_Loan_Amount,Credit_Score,Annual_Income,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,99999999,741.0,2231892.0,29200.53,14.9,29.0,18,1,297996,750090.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,217646,730.0,1184194.0,10855.08,19.6,10.0,13,1,122170,272052.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,548746,678.0,2559110.0,18660.28,22.6,33.0,4,0,437171,555038.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,99999999,728.0,714628.0,11851.06,16.0,76.0,16,0,203965,289784.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,99999999,740.0,776188.0,11578.22,8.5,25.0,6,0,134083,220220.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36418,99999999,742.0,1190046.0,11969.81,20.1,16.0,9,0,37392,134442.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36419,44484,717.0,1152426.0,6280.64,21.0,12.0,6,0,961932,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36420,210584,719.0,783389.0,3727.61,17.4,18.0,6,0,456,259160.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36421,99999999,732.0,1289416.0,13109.05,9.4,21.0,22,0,153045,509234.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
36422,103136,742.0,1150545.0,7315.57,18.8,18.0,12,1,109554,537548.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [7]:
# Remove loan status target from features data
y = loans_df.Loan_Status_Fully_Paid
X = loans_df.drop(columns=["Loan_Status_Fully_Paid","Loan_Status_Not_Paid"])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.849

In [9]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 24
hidden_nodes_layer2 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

2022-08-17 11:13:15.101470: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Epoch 1/50
854/854 [==============================] - 2s 2ms/step - loss: 0.4237 - accuracy: 0.8351
Epoch 2/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3875 - accuracy: 0.8491
Epoch 3/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3828 - accuracy: 0.8494
Epoch 4/50
854/854 [==============================] - 2s 3ms/step - loss: 0.3810 - accuracy: 0.8494
Epoch 5/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3798 - accuracy: 0.8494
Epoch 6/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3782 - accuracy: 0.8496
Epoch 7/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3775 - accuracy: 0.8497
Epoch 8/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3764 - accuracy: 0.8495
Epoch 9/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3759 - accuracy: 0.8497
Epoch 10/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3756 - accuracy: 0.8497
Epoch 11/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3748 - accuracy: 0.8497
Epoch 12/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3743 - accuracy: 0.8498
Epoch 13/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3737 - accuracy: 0.8499
Epoch 14/50
854/854 [==============================] - 2s 3ms/step - loss: 0.3732 - accuracy: 0.8501
Epoch 15/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3730 - accuracy: 0.8495
Epoch 16/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3724 - accuracy: 0.8500
Epoch 17/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3720 - accuracy: 0.8502
Epoch 18/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3717 - accuracy: 0.8502
Epoch 19/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3714 - accuracy: 0.8503
Epoch 20/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3706 - accuracy: 0.8503
Epoch 21/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3704 - accuracy: 0.8505
Epoch 22/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3703 - accuracy: 0.8506
Epoch 23/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3699 - accuracy: 0.8506
Epoch 24/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3697 - accuracy: 0.8504
Epoch 25/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3692 - accuracy: 0.8506
Epoch 26/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3689 - accuracy: 0.8508
Epoch 27/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3687 - accuracy: 0.8514
Epoch 28/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3683 - accuracy: 0.8510
Epoch 29/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3678 - accuracy: 0.8515
Epoch 30/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3673 - accuracy: 0.8513
Epoch 31/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3670 - accuracy: 0.8519
Epoch 32/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3668 - accuracy: 0.8512
Epoch 33/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3668 - accuracy: 0.8520
Epoch 34/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3663 - accuracy: 0.8520
Epoch 35/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3662 - accuracy: 0.8516
Epoch 36/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3661 - accuracy: 0.8517
Epoch 37/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3654 - accuracy: 0.8519
Epoch 38/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3651 - accuracy: 0.8524
Epoch 39/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3651 - accuracy: 0.8523
Epoch 40/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3644 - accuracy: 0.8519
Epoch 41/50
854/854 [==============================] - 2s 3ms/step - loss: 0.3643 - accuracy: 0.8520
Epoch 42/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3637 - accuracy: 0.8527
Epoch 43/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3630 - accuracy: 0.8529
Epoch 44/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3638 - accuracy: 0.8531
Epoch 45/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3634 - accuracy: 0.8529
Epoch 46/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3629 - accuracy: 0.8529
Epoch 47/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3632 - accuracy: 0.8528
Epoch 48/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3627 - accuracy: 0.8531
Epoch 49/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3623 - accuracy: 0.8529
Epoch 50/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3618 - accuracy: 0.8537
285/285 - 0s - loss: 0.3933 - accuracy: 0.8444 - 463ms/epoch - 2ms/step
Loss: 0.3933262825012207, Accuracy: 0.8443883061408997